Update cppcheck.yml

diff --git a/.github/workflows/cppcheck.yml b/.github/workflows/cppcheck.yml
--- a/.github/workflows/cppcheck.yml
+++ b/.github/workflows/cppcheck.yml
@@ -19,38 +19,22 @@ jobs:
           
       - name: print output
         run: |
-          sudo apt-get install rpl
-          REPORTFILE=./cppcheck_report.txt
+          REPORTFILE=./report.txt
+          WARNINGSFILE=./warnings.txt
           if test -f "$REPORTFILE"; then
-            # filter innocuous warnings and write the remaining ones to another file
-            cat "$REPORTFILE" |
-            rpl -w "missingIncludeSystem" "" |
-            rpl -w "useStlAlgorithmZZZ" "" > warnings.txt
-            
-            if grep -qP '\[[a-zA-Z0-9]+\]' warnings.txt
-              then 
-                 echo "Warnings detected";
-             else
-                exit 0;
-            fi
-            
-            echo step 1
-            
-            cat warnings.txt |
-            grep -P '\[[a-zA-Z0-9]+\]' > warnings.txt
-            
-            echo step 2
-            
-            WARNINGCOUNT="$(wc -l < warnings.txt)"
-            MAXWARNINGS=0
-            if [ "$WARNINGCOUNT" -gt "$MAXWARNINGS" ]; then
-              # print the warnings
-              echo Warnings Found:
-              echo ===============
-              cat warnings.txt
-              # fail the job
-              exit 1
-            fi
+              # Filter innocuous warnings and write the remaining ones to another file.
+              # Note that you can add more warnings by adding it in the parenthesis,
+              # with "\|" in front of it. For example, "(missingIncludeSystem\|useStlAlgorithm\)"
+              sed 's/\[\(missingIncludeSystem\|useStlAlgorithm\)\]//g' "$REPORTFILE" > "$WARNINGSFILE"
+              # are there any remaining warnings?
+              if grep -qP '\[[a-zA-Z0-9]+\]' "$WARNINGSFILE"; then
+                  # print the remaining warnings
+                  echo Warnings detected:
+                  echo ==================
+                  cat "$WARNINGSFILE" | grep -P '\[[a-zA-Z0-9]+\]'
+                  # fail the job
+                  exit 1
+              else
+                  echo No warnings detected
+              fi
           fi
-          echo No warnings found
-          exit 0
