Update cppcheck.yml

diff --git a/.github/workflows/cppcheck.yml b/.github/workflows/cppcheck.yml
--- a/.github/workflows/cppcheck.yml
+++ b/.github/workflows/cppcheck.yml
@@ -21,16 +21,17 @@ jobs:
         run: |
           REPORTFILE=./cppcheck_report.txt
           if test -f "$REPORTFILE"; then
-          # filter innocuous warnings and write the remaining ones to another file
-          sed 's/\[includeystem\]//g' "$REPORTFILE" | grep -P '\[[a-zA-Z0-9]+\]' > warnings.txt
-          WARNINGCOUNT="$(wc -l < warnings.txt)"
-          MAXWARNINGS=0
-          if [ "$WARNINGCOUNT" -gt "$MAXWARNINGS" ]; then
-          # print the warnings
-          echo Warnings Found:
-          echo ===============
-          cat warnings.txt
-          # fail the job
-          exit 1
-          fi
+            # filter innocuous warnings and write the remaining ones to another file
+            sed 's/\[missingIncludeSystem\]//g' "$REPORTFILE" | \
+            grep -P '\[[a-zA-Z0-9]+\]' > warnings.txt
+            WARNINGCOUNT="$(wc -l < warnings.txt)"
+            MAXWARNINGS=0
+            if [ "$WARNINGCOUNT" -gt "$MAXWARNINGS" ]; then
+              # print the warnings
+              echo Warnings Found:
+              echo ===============
+              cat warnings.txt
+              # fail the job
+              exit 1
+            fi
           fi
