Update i18n-check.yml

diff --git a/.github/workflows/i18n-check.yml b/.github/workflows/i18n-check.yml
--- a/.github/workflows/i18n-check.yml
+++ b/.github/workflows/i18n-check.yml
@@ -22,3 +22,24 @@ jobs:
         run: |
              ./i18n-check/bin/i18n-check ./ --ignore=i18n-check -q -o wxSPresults.txt
              cat wxSPresults.txt
+             
+      - name: print output
+        run: |
+             REPORTFILE=./wxSPresults.txt
+             WARNINGSFILE=./warnings.txt
+             if test -f "$REPORTFILE"; then
+                cat "$REPORTFILE" > "$WARNINGSFILE"
+                # are there any warnings?
+                if grep -qP '\[[a-zA-Z0-9]+\]' "$WARNINGSFILE"; then
+                    # print the remaining warnings
+                    echo Warnings detected:
+                    echo ==================
+                    cat "$WARNINGSFILE" | grep -P '\[[a-zA-Z0-9]+\]'
+                    # fail the job
+                    exit 1
+                else
+                    echo No warnings detected
+                fi
+             else
+                echo "$REPORTFILE" not found
+             fi
